# Generated by Django 2.0.7 on 2022-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHATROOMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=5000)),
                ('itemid', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=5000)),
                ('msg', models.CharField(max_length=10000)),
                ('userid', models.CharField(max_length=5000)),
            ],
        ),
    ]
