# Generated by Django 2.0.7 on 2022-08-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_chatrooms_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrooms',
            old_name='itemid',
            new_name='roomid',
        ),
        migrations.RemoveField(
            model_name='chatrooms',
            name='room',
        ),
    ]
